### ISSUE TITLE
Interesting work and i will follow！

### ISSUE THREAD

**Issue by myz12138** [Zizhao-Wang/REXIO#1]
Interesting work and i will follow！

**Comment by Zizhao-Wang** [comment]
Thank you and if you any questions, feel free to contact me.

**Comment by myz12138** [comment]
v me 50 for Thursday



---Original---
From: "Zizhao ***@***.***&gt;
Date: Sat, Sep 7, 2024 12:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Zizhao-Wang/REXIO] Interesting work and i will follow！ (Issue #1)




 
Thank you and if you any questions, feel free to contact me.
